#!/bin/bash

case $# in
    0)
        echo "Convert long, horizontal videos to short, vertical videos suitable for TikTok"
        echo "Usage: $(basename $0) [HH:MM:SS(.xxx) HH:MM:SS(.xxx)] input.mp4 [output.mp4]"
        exit 1
        ;;
    1)
        input_filename="$1"
        output_filename="${1%.*}"_cropped."${1##*.}"
        ;;
    2)
        input_filename="$1"
        output_filename="$2"
        ;;
    3)
        start_ts="$1"
        end_ts="$2"
        input_filename="$3"
        output_filename="${3%.*}"_"$1"-"$2"."${3##*.}"
        ;;
    4)
        start_ts="$1"
        end_ts="$2"
        input_filename="$3"
        output_filename="$4"
        ;;
esac

secret_formula="in_w*9/16*9/16:in_w*9/16:0.5*in_w-0.5*out_w:0"

if [[ -z "$start_ts" ]]
then
    ffmpeg -i "$input_filename" \
           -c:v libx264 \
           -filter:v "crop=$secret_formula" \
           "$output_filename"
else
    ffmpeg -ss "$start_ts" \
           -i "$input_filename" \
           -to "$end_ts" \
           -copyts \
           -c:v libx264 \
           -filter:v "crop=$secret_formula" \
           "$output_filename"
fi

ffplay "$output_filename"
